# subtitles.py
# -------------------------------------------------------------
# Subtitle handling (SRT + ASS)
# -------------------------------------------------------------

import os, re, textwrap

# ------------------------------- #
#        Time formatting          #
# ------------------------------- #
def fmt_srt_time(ms: int) -> str:
    """Convert milliseconds → SRT timestamp"""
    h = ms // 3_600_000
    m = (ms % 3_600_000) // 60_000
    s = (ms % 60_000) // 1000
    ms2 = ms % 1000
    return f"{h:02}:{m:02}:{s:02},{ms2:03}"

def fmt_ass_time(ms: int) -> str:
    """Convert milliseconds → ASS timestamp (centisecond grid)"""
    cs_total = int(round(ms / 10))
    h = cs_total // 360000
    m = (cs_total % 360000) // 6000
    s = (cs_total % 6000) // 100
    cs = cs_total % 100
    return f"{h}:{m:02}:{s:02}.{cs:02}"

def round_to_ass_grid(ms: int) -> int:
    """Snap ms to ASS 10ms grid"""
    return int(round(ms / 10.0)) * 10

# ------------------------------- #
#          SRT Writing            #
# ------------------------------- #
def write_srt_from_cues(cues, path):
    """Write subtitle cues into SRT file"""
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        for i, c in enumerate(cues, start=1):
            f.write(f"{i}\n{fmt_srt_time(c['start'])} --> {fmt_srt_time(c['end'])}\n{c['text']}\n\n")

# ------------------------------- #
#          SRT Parsing            #
# ------------------------------- #
def parse_srt(path: str):
    """Read SRT file and return list of cues"""
    def _parse_time(t):
        h, m, rest = t.split(":")
        s, ms = rest.split(",")
        return (int(h)*3600 + int(m)*60 + int(s))*1000 + int(ms)
    cues, buf, start, end = [], [], None, None
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line.strip():
                if start is not None:
                    cues.append({"start": start, "end": end, "text": "\n".join(buf).strip()})
                buf, start, end = [], None, None
                continue
            if "-->" in line:
                t1, t2 = [x.strip() for x in line.split("-->")]
                start, end = _parse_time(t1), _parse_time(t2)
            elif line.strip().isdigit() and start is None:
                continue
            else:
                buf.append(line)
        if start is not None:
            cues.append({"start": start, "end": end, "text": "\n".join(buf).strip()})
    return cues

# ------------------------------- #
#          ASS Writing            #
# ------------------------------- #
def write_ass_from_cues(cues, path, video_w, video_h, base_font="Arial", base_fs=32):
    """Write ASS subtitles with auto-sizing and line wrapping"""
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)

    margin_lr = 100
    usable_w  = video_w - 2 * margin_lr
    cx, cy    = video_w // 2, video_h // 2

    def wrap_and_autosize(text, base_fs, max_width_px, max_lines=3, min_fs=18):
        text2 = re.sub(r"\s+", " ", text.strip())
        def per_line_limit(fs):
            avg_char_w = 0.56 * fs
            return max(5, int(max_width_px / max(avg_char_w, 1)))
        fs = base_fs
        while fs >= min_fs:
            limit = per_line_limit(fs)
            wrapped = textwrap.wrap(text2, width=limit)
            if len(wrapped) <= max_lines and wrapped:
                max_len = max(len(line) for line in wrapped)
                if (0.56 * fs * max_len) <= max_width_px:
                    return fs, r"\N".join(wrapped)
            fs -= 2
        wrapped = textwrap.wrap(text2, width=per_line_limit(min_fs)) or [text2]
        return min_fs, r"\N".join(wrapped)

    header = f"""[Script Info]
; Script generated by Python
ScriptType: v4.00+
WrapStyle: 2
ScaledBorderAndShadow: yes
PlayResX: {video_w}
PlayResY: {video_h}

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Main,{base_font},{base_fs},&H00FFFFFF,&H000000FF,&H00000000,&H66000000,0,0,0,0,100,100,0,0,1,4,0,5,0,0,0,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
    with open(path, "w", encoding="utf-8") as f:
        f.write(header)
        for c in cues:
            start_s = fmt_ass_time(c["start"])
            end_s   = fmt_ass_time(c["end"])
            fs, wrapped = wrap_and_autosize(c["text"], base_fs, usable_w, max_lines=3, min_fs=18)
            ass_text = r"{\an5\pos(" + f"{cx},{cy}" + r")\fs" + str(fs) + "}" + wrapped
            f.write(f"Dialogue: 0,{start_s},{end_s},Main,,0,0,0,,{ass_text}\n")
